local ffi=require('ffi')
local Memory=dofile('src/native_ui/bingus_memory.lua');local Runtime=dofile('src/native_ui/bingus_runtime.lua')
local memory=Memory.new(Runtime);local buffer=ffi.new('uint8_t[8]',{77,67,77,0,1,2,3,4})
local address=tonumber(ffi.cast('uintptr_t',buffer))
local ok=pcall(memory.read,address,8);assert(not ok,'numeric address unexpectedly bypassed pointer contract')
assert(memory.read(ffi.cast('const void *',address),8)=='MCM\0\1\2\3\4')
local output=ffi.new('uint8_t[8]');assert(memory.read_into(ffi.cast('const void *',address),8,output));assert(ffi.string(output,8)=='MCM\0\1\2\3\4')
assert(memory.writable_data(address,8),'own FFI heap was not writable private memory')
print('PASS actual Windows ReadProcessMemory pointer contract and VirtualQuery against own allocated buffer; no game attached')
